// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a757de7b-812f-4fcb-aee3-f3b36aaa5784",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TnInisL30",
    "aws_user_pools_web_client_id": "319b8p0it89am1tu2557atiutl",
    "aws_appsync_graphqlEndpoint": "https://3taeqiy635h53cl46r6oqz32di.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cxzcy7jtsjakpnyjase33odpim",
    "aws_cloud_logic_custom": [
        {
            "name": "tasklistlambdaapi",
            "endpoint": "https://myyn8h300g.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
